### ISSUE TITLE
Use colortheme for framesubtitle

### ISSUE THREAD

**Issue by Thyrum** [TAdeJong/beamer-universiteit-leiden#2]
I personally think it looks more clean for the subtitle to have the same color as the colortheme (orange for fwn, lightblue for lumc). Wat are your thoughts on this? If we want this a quickfix would be
```LaTeX
\setbeamercolor{framesubtitle}{use={palette primary},fg=palette primary.bg}
```
but I personally don't think this is the cleanest (since your using a `bg` color for your `fg`). Maybe you know a better way to implement this.

**Comment by TAdeJong** [comment]
Lots of thoughts, no clear unique solution or cleaner way to implement.

- Another option aside from the colortheme would be to introduce a secondary more bland blue, as the powerpoint themes do.
- However, now we have quiet a lot of different solutions. `\setbeamercolor` can if I am not mistaken be used in the body of the tex itself. Although also not very 'clean', we could note this in the readme for users. This would mean throwing this in a readme, introducing and a bland blue as an option?

**Comment by Thyrum** [comment]
Although I do prefer using the main colortheme color I do see the value of adhering to the existing powerpoint template. I think it is best to adhere to the powerpoint template by default and mention the option of manually setting the subtitle color in the README. Maybe we even want to add it to the `.tex` files but comment it out with a comment explaining it.

**Comment by Thyrum** [comment]
And now that I'm thinking about it, including info about how to disable the presentation controls that are included by default can't hurt either. I think those controls don't look professional and disable them most of the time. This can be done by including
```LaTeX
\setbeamertemplate{navigation symbols}{}%remove navigation symbols
```
As with the previous one, I'd propose including it as a comment with explanation and maybe even adding it to the README.
